- name: "Ensure group exists {{ user }}"
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: "Ensure user exists {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    password: "$6$rounds=4096$NoxU8eTt21Z/BlWd$9HwIoxOe9s8RPSjh/RxTCH4wB5DujiOmB7kd21BbmRk7ZvszAjBBgNZSf/aqY6dmXPxKZK6WCMLI94zFNTo7i0"
    create_home: true
    shell: /bin/bash
    group: pcpc
    groups:
      - sudo

- name: Ensure SSH password authentication is enabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    state: absent
  register: sshd_config

- name: Restart ssh service
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: sshd_config is changed
