- name: "Lab4"
  hosts: all

  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Load variables file
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - 'vars/servers-{{ ansible_os_family }}.yml'
        - vars/servers-default.yml

  tasks:
    - name: Copy MPI sources
      ansible.builtin.copy:
        src: "./sources/{{ item }}"
        dest: '/home/{{ user }}/{{ item }}'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0777'
      loop: "{{ sources }}"

    - name: Compile MPI sources
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'mpicc "/home/{{ user }}/{{ item }}" -o "/home/{{ user }}/{{ item }}.out"'
      loop: "{{ sources }}"

    - name: Copy host file on master
      ansible.builtin.copy:
        src: './hfile'
        dest: '/home/{{ user }}/hfile'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0777'
      run_once: true

    - name: Run MPI sources on master
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'mpirun -np 4 --oversubscribe --hostfile "/home/{{ user }}/hfile" "/home/{{ user }}/{{ item }}.out"'
      loop: "{{ sources }}"
      when: 'item != "lab4_2.c"'
      register: mpi_output
      run_once: true

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ mpi_output.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: '"stdout_lines" in item'
      run_once: true

    - name: Run MPI lab4_2 on master
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'mpirun -np 4 --oversubscribe --hostfile "/home/{{ user }}/hfile" "/home/{{ user }}/lab4_2.c.out"'
        stdin: "hello"
        stdin_add_newline: true
      register: mpi_output_lab4_2
      run_once: true

    - name: Print lab4_2 output
      ansible.builtin.debug:
        msg: "{{ mpi_output_lab4_2.stdout_lines }}"
      run_once: true
