- name: "Lab6"
  hosts: all

  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Load variables file
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "vars/servers-{{ ansible_os_family }}.yml"
        - vars/servers-default.yml

  tasks:
    - name: Copy MPI sources
      ansible.builtin.copy:
        src: "./sources/{{ item }}"
        dest: "/home/{{ user }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0777"
      loop: "{{ sources }}"

    - name: Compile MPI sources
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'mpicc "/home/{{ user }}/{{ item }}" -o "/home/{{ user }}/{{ item }}.out"'
      loop: "{{ sources }}"
      when: "item not in ignore_compile"

    - name: Copy host file on master
      ansible.builtin.copy:
        src: "./hfile"
        dest: "/home/{{ user }}/hfile"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0777"
      run_once: true

    - name: Run MPI sources on master
      become_user: "{{ user }}"
      ansible.builtin.command:
        cmd: 'mpirun -np {{ P }} --oversubscribe --hostfile "/home/{{ user }}/hfile" "/home/{{ user }}/{{ item }}.out"'
      loop: "{{ sources }}"
      when: "item not in ignore_run"
      register: mpi_output
      run_once: true

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ mpi_output.results }}"
      when: "item.item not in ignore_run"
      loop_control:
        label: "{{ item.item }}"
      run_once: true
