---
- name: 'Generate ssh keys on localhost'
  hosts: localhost

  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Load variables file
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - 'vars/servers-{{ ansible_os_family }}.yml'
        - vars/servers-default.yml

  tasks:
    - name: 'Generate keys'
      community.crypto.openssh_keypair:
        path: '{{ local_ssh_dir }}/{{ user }}'

- name: 'Add user and ssh keys'
  hosts: all

  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Load variables file
      ansible.builtin.include_vars: '{{ item }}'
      with_first_found:
        - 'vars/servers-{{ ansible_os_family }}.yml'
        - vars/servers-default.yml

    - name: Apt update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 24h

  tasks:
    - name: Setup user
      ansible.builtin.import_tasks: tasks/user.yml

    - name: Setup ssh-keys
      ansible.builtin.import_tasks: tasks/ssh-keys.yml

    - name: Install MPI
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - openmpi-bin
        - openmpi-common
        - openmpi-doc
        - libopenmpi-dev
        - gcc
        - htop